repos:
  - repo: https://github.com/PyCQA/pylint
    rev: v2.17.4
    hooks:
      - id: pylint
        args:
          - --max-line-length=120
          - --disable=C0103,C0114,C0115,C0116,R0903,R0913,W0707,W0236,E0401,logging-fstring-interpolation

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
