name: Run Apartments Finder

on:
  schedule:
    - cron: "0 8 * * *"  # כל יום ב־08:00 UTC (11:00 שעון ישראל)
  workflow_dispatch:      # מאפשר להריץ גם ידנית

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      FACEBOOK_USERNAME: ${{ secrets.FACEBOOK_USERNAME }}
      FACEBOOK_PASSWORD: ${{ secrets.FACEBOOK_PASSWORD }}
      FACEBOOK_GROUPS: ${{ secrets.FACEBOOK_GROUPS }}
      TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_API_KEY }}
      TELEGRAM_BOT_APARTMENTS_GROUP_CHAT_ID: ${{ secrets.TELEGRAM_BOT_APARTMENTS_GROUP_CHAT_ID }}
      TELEGRAM_BOT_APARTMENTS_LOGS_GROUP_CHAT_ID: ${{ secrets.TELEGRAM_BOT_APARTMENTS_LOGS_GROUP_CHAT_ID }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: python -m apartments_finder.main
